# Generated by Django 4.2.7 on 2026-01-06 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("menu_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemenuitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="recipemenuitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
