# Generated by Django 4.2.7 on 2026-01-06 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_management", "0002_recipemenuitem_created_at_recipemenuitem_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="menu_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("bar", "Bar"),
                    ("dessert", "Dessert"),
                    ("catering", "Catering"),
                    ("seasonal", "Seasonal"),
                    ("tasting", "Tasting Menu"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="VirtualBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "brand_type",
                    models.CharField(
                        choices=[
                            ("fast_casual", "Fast Casual"),
                            ("fine_dining", "Fine Dining"),
                            ("cafe", "Cafe"),
                            ("bakery", "Bakery"),
                            ("pizza", "Pizza"),
                            ("asian", "Asian Cuisine"),
                            ("healthy", "Healthy"),
                            ("desserts", "Desserts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_market",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("urban", "Urban"),
                            ("suburban", "Suburban"),
                            ("office", "Office"),
                            ("college", "College"),
                            ("family", "Family"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="brand_logos/")),
                ("brand_color", models.CharField(default="#667eea", max_length=7)),
                ("uber_eats_active", models.BooleanField(default=True)),
                ("doordash_active", models.BooleanField(default=True)),
                ("grubhub_active", models.BooleanField(default=False)),
                (
                    "base_markup",
                    models.DecimalField(decimal_places=2, default=300.0, max_digits=5),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=2.99, max_digits=5),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("uber_eats", "Uber Eats"),
                            ("doordash", "DoorDash"),
                            ("grubhub", "Grubhub"),
                            ("postmates", "Postmates"),
                            ("seamless", "Seamless"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
                ("platform_menu_id", models.CharField(blank=True, max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.virtualbrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_type", models.CharField(max_length=50)),
                ("priority", models.CharField(default="medium", max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("expected_impact", models.CharField(max_length=100)),
                (
                    "implementation_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.virtualbrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GhostKitchenWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("avg_preparation_time", models.IntegerField(default=0)),
                ("capacity_per_hour", models.IntegerField(default=0)),
                (
                    "efficiency_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("optimization_suggestions", models.JSONField(default=list)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.virtualbrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharedIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_frequency", models.IntegerField(default=0)),
                (
                    "cost_optimization",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.virtualbrand",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient", "brand")},
            },
        ),
        migrations.CreateModel(
            name="BrandPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("top_items", models.JSONField(default=dict)),
                (
                    "customer_ratings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.virtualbrand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "date")},
            },
        ),
    ]
