# Generated by Django 4.2.7 on 2026-01-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        (
            "menu_management",
            "0003_alter_menu_menu_type_alter_menu_name_virtualbrand_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("prep", "Prep Station"),
                            ("grill", "Grill Station"),
                            ("sauté", "Sauté Station"),
                            ("fry", "Fry Station"),
                            ("cold", "Cold Prep Station"),
                            ("pastry", "Pastry Station"),
                            ("packaging", "Packaging Station"),
                            ("expedite", "Expedite Station"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=5)),
                ("current_load", models.IntegerField(default=0)),
                ("efficiency_score", models.IntegerField(default=100)),
                ("avg_preparation_time", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("equipment", models.JSONField(default=list)),
                ("capabilities", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_assigned",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_received", "Order Received"),
                            ("order_started", "Order Started"),
                            ("order_ready", "Order Ready"),
                            ("order_completed", "Order Completed"),
                            ("station_alert", "Station Alert"),
                            ("low_inventory", "Low Inventory"),
                            ("equipment_issue", "Equipment Issue"),
                            ("staff_message", "Staff Message"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("message_template", models.TextField()),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("default_expires_minutes", models.IntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("conditions", models.JSONField(default=dict)),
                ("station_preferences", models.JSONField(default=list)),
                ("priority", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StationPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("orders_processed", models.IntegerField(default=0)),
                ("avg_time_per_order", models.FloatField(default=0)),
                ("accuracy_score", models.IntegerField(default=100)),
                ("efficiency_score", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routing_score", models.IntegerField(default=0)),
                ("estimated_time", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=5)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_notifications", models.BooleanField(default=True)),
                ("station_alerts", models.BooleanField(default=True)),
                ("inventory_alerts", models.BooleanField(default=True)),
                ("system_alerts", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=False)),
                ("sound_notifications", models.BooleanField(default=True)),
                (
                    "min_priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_received", "Order Received"),
                            ("order_started", "Order Started"),
                            ("order_ready", "Order Ready"),
                            ("order_completed", "Order Completed"),
                            ("station_alert", "Station Alert"),
                            ("low_inventory", "Low Inventory"),
                            ("equipment_issue", "Equipment Issue"),
                            ("staff_message", "Staff Message"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
