# Generated by Django 4.2.7 on 2026-01-06 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "menu_management",
            "0004_kitchenstation_notificationtemplate_routingrule_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("probe", "Probe Thermometer"),
                            ("infrared", "Infrared Thermometer"),
                            ("ambient", "Ambient Sensor"),
                            ("refrigeration", "Refrigeration Sensor"),
                            ("freezer", "Freezer Sensor"),
                            ("cooking", "Cooking Sensor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sensor_id", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("current_temp", models.FloatField()),
                ("target_temp", models.FloatField()),
                ("min_safe_temp", models.FloatField()),
                ("max_safe_temp", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("food_item", models.CharField(blank=True, max_length=100)),
                ("measurement_context", models.CharField(blank=True, max_length=100)),
                ("is_within_range", models.BooleanField()),
                ("alert_triggered", models.BooleanField(default=False)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HACCPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccp",
                    models.CharField(
                        choices=[
                            ("receiving", "Receiving"),
                            ("storage", "Storage"),
                            ("preparation", "Preparation"),
                            ("cooking", "Cooking"),
                            ("cooling", "Cooling"),
                            ("reheating", "Reheating"),
                            ("holding", "Holding"),
                            ("serving", "Serving"),
                            ("cleaning", "Cleaning"),
                            ("pest_control", "Pest Control"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("critical_limit", models.CharField(max_length=200)),
                ("actual_value", models.CharField(max_length=200)),
                ("is_within_limit", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("requires_corrective_action", models.BooleanField(default=False)),
                ("corrective_action_taken", models.TextField(blank=True)),
                ("corrective_action_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("supporting_documents", models.JSONField(default=list)),
                (
                    "corrective_action_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haccp_corrective_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haccp_monitored_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haccp_verified_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodSafetyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("temperature_check", "Temperature Check"),
                            ("sanitation_check", "Sanitation Check"),
                            ("equipment_check", "Equipment Check"),
                            ("pest_control", "Pest Control"),
                            ("food_preparation", "Food Preparation"),
                            ("storage_check", "Storage Check"),
                            ("delivery_inspection", "Delivery Inspection"),
                            ("allergen_control", "Allergen Control"),
                            ("staff_hygiene", "Staff Hygiene"),
                            ("waste_disposal", "Waste Disposal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("corrective_action", "Corrective Action Required"),
                            ("resolved", "Resolved"),
                        ],
                        default="compliant",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("station", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("target_temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_automated", models.BooleanField(default=False)),
                ("sensor_data", models.JSONField(default=dict)),
                ("compliance_score", models.IntegerField(default=100)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["log_type", "timestamp"],
                        name="menu_manage_log_typ_c66f53_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="menu_manage_status_e2b2bb_idx",
                    ),
                    models.Index(
                        fields=["location", "timestamp"],
                        name="menu_manage_locatio_cc731c_idx",
                    ),
                ],
            },
        ),
    ]
