# Generated by Django 4.2.7 on 2026-01-06 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_management", "0006_communication_inventorybatch_inventoryitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergenControl",
            fields=[
                (
                    "control_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("allergens_present", models.JSONField(default=list)),
                ("control_measures", models.JSONField(default=list)),
                ("cleaning_protocols", models.JSONField(default=list)),
                ("staff_trained", models.JSONField(default=list)),
                ("last_training_date", models.DateField(blank=True, null=True)),
                ("last_audit", models.DateField(blank=True, null=True)),
                ("audit_results", models.JSONField(default=list)),
                ("incidents", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseMenu",
            fields=[
                (
                    "menu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("table_number", models.CharField(max_length=20)),
                ("customer_count", models.IntegerField(default=1)),
                ("courses", models.JSONField(default=list)),
                ("current_course", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_duration", models.IntegerField(default=120)),
                ("pacing_interval", models.IntegerField(default=15)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sommelier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sommelier_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalThermometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("thermometer_type", models.CharField(max_length=50)),
                ("last_calibration", models.DateField()),
                ("next_calibration", models.DateField()),
                (
                    "calibration_offset",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("api_endpoint", models.URLField(blank=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_id", models.CharField(max_length=100, unique=True)),
                ("equipment_name", models.CharField(max_length=200)),
                ("equipment_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("maintenance_frequency", models.CharField(max_length=50)),
                ("last_maintenance", models.DateField()),
                ("next_maintenance", models.DateField()),
                ("maintenance_tasks", models.JSONField(default=list)),
                ("parts_required", models.JSONField(default=list)),
                ("service_provider", models.CharField(blank=True, max_length=200)),
                ("contact_info", models.TextField(blank=True)),
                ("is_operational", models.BooleanField(default=True)),
                ("issues_reported", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HealthInspection",
            fields=[
                (
                    "inspection_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspector_name", models.CharField(max_length=200)),
                ("inspection_agency", models.CharField(max_length=200)),
                ("inspection_type", models.CharField(max_length=50)),
                ("preparation_checklist", models.JSONField(default=list)),
                ("preparation_completed", models.BooleanField(default=False)),
                ("inspection_result", models.CharField(blank=True, max_length=20)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("violations", models.JSONField(default=list)),
                ("corrective_actions_required", models.JSONField(default=list)),
                ("reinspection_date", models.DateField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(blank=True, upload_to="inspection_reports/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenDisplaySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_type", models.CharField(max_length=50)),
                ("station_filter", models.JSONField(default=list)),
                ("max_orders_displayed", models.IntegerField(default=20)),
                ("auto_refresh_interval", models.IntegerField(default=5)),
                ("show_completed_orders", models.BooleanField(default=True)),
                ("completed_orders_timeout", models.IntegerField(default=30)),
                ("layout_config", models.JSONField(default=dict)),
                ("color_scheme", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenOrder",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_order_id", models.CharField(blank=True, max_length=100)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("dine_in", "Dine In"),
                            ("takeout", "Takeout"),
                            ("delivery", "Delivery"),
                            ("catering", "Catering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("table_number", models.CharField(blank=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("cooking", "Cooking"),
                            ("plating", "Plating"),
                            ("quality_check", "Quality Check"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("estimated_prep_time", models.IntegerField(help_text="Minutes")),
                ("actual_prep_time", models.IntegerField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("dietary_restrictions", models.JSONField(default=list)),
                ("allergen_alerts", models.JSONField(default=list)),
                ("is_rush_order", models.BooleanField(default=False)),
                ("is_vip_order", models.BooleanField(default=False)),
                ("course_sequence", models.IntegerField(default=1)),
                ("total_courses", models.IntegerField(default=1)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expedited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedited_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_orders",
                        to="menu_management.kitchenorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pos", "POS System"),
                            ("online", "Online Ordering"),
                            ("delivery", "Delivery Platform"),
                            ("phone", "Phone Order"),
                            ("walkin", "Walk-in"),
                            ("kiosk", "Self-service Kiosk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_endpoint", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("integration_settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrepItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("prep_method", models.TextField()),
                ("prep_time", models.IntegerField(help_text="Minutes")),
                ("batch_size", models.IntegerField(default=1)),
                (
                    "yield_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("yield_unit", models.CharField(max_length=50)),
                ("storage_requirements", models.TextField(blank=True)),
                ("shelf_life_hours", models.IntegerField(default=24)),
                ("par_level", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "ingredient_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SanitationChecklist",
            fields=[
                (
                    "checklist_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("equipment", models.CharField(blank=True, max_length=100)),
                ("items", models.JSONField(default=list)),
                ("checklist_date", models.DateField()),
                ("checklist_type", models.CharField(max_length=50)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("issues_found", models.JSONField(default=list)),
                ("corrective_actions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_sanitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_sanitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrepTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "target_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "completed_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "waste_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("actual_duration", models.IntegerField(blank=True, null=True)),
                ("quality_notes", models.TextField(blank=True)),
                (
                    "yield_variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_management.kitchenstation",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prep_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prep_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.prepitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrepChecklist",
            fields=[
                (
                    "checklist_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("items", models.JSONField(default=list)),
                ("checklist_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackagingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("packaging_types", models.JSONField(default=list)),
                ("quality_checkpoints", models.JSONField(default=list)),
                ("capacity_per_hour", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_assigned",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_item", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("modifications", models.JSONField(default=list)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("cooking", "Cooking"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("preparation_time", models.IntegerField(default=10)),
                ("fire_time", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_management.kitchenstation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu_management.kitchenorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderBatch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "preparation_time",
                    models.IntegerField(help_text="Similar prep time in minutes"),
                ),
                ("cooking_method", models.CharField(max_length=100)),
                ("packaging_type", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "efficiency_gain",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orders",
                    models.ManyToManyField(
                        related_name="order_batches", to="menu_management.kitchenorder"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KitchenTemperatureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("cooking", "Cooking"),
                            ("cooling", "Cooling"),
                            ("holding", "Holding"),
                            ("storage", "Storage"),
                            ("receiving", "Receiving"),
                            ("serving", "Serving"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("food_item", models.CharField(blank=True, max_length=200)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("current_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("target_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("min_safe_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_safe_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("is_within_range", models.BooleanField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("alert_triggered", models.BooleanField(default=False)),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thermometer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_management.digitalthermometer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_temps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kitchenorder",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu_management.ordersource",
            ),
        ),
        migrations.CreateModel(
            name="FoodSafetyCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_type", models.CharField(max_length=100)),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_current", models.BooleanField(default=True)),
                ("training_hours", models.IntegerField(default=0)),
                ("training_topics", models.JSONField(default=list)),
                ("renewal_required", models.BooleanField(default=False)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverHandoff",
            fields=[
                (
                    "handoff_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_platform", models.CharField(max_length=100)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_phone", models.CharField(max_length=20)),
                ("estimated_pickup", models.DateTimeField()),
                ("actual_pickup", models.DateTimeField(blank=True, null=True)),
                ("packaging_verified", models.BooleanField(default=False)),
                ("temperature_verified", models.BooleanField(default=False)),
                ("quality_verified", models.BooleanField(default=False)),
                ("handoff_issues", models.TextField(blank=True)),
                ("customer_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.kitchenorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_number", models.IntegerField()),
                ("course_name", models.CharField(max_length=200)),
                ("scheduled_start", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_completion", models.DateTimeField()),
                ("actual_completion", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("dietary_accommodations", models.JSONField(default=list)),
                ("special_plating", models.TextField(blank=True)),
                (
                    "course_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_timings",
                        to="menu_management.coursemenu",
                    ),
                ),
                (
                    "kitchen_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_management.kitchenstation",
                    ),
                ),
                (
                    "plating_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plating_courses",
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssemblyLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("steps", models.JSONField(default=list)),
                ("capacity_per_hour", models.IntegerField(default=50)),
                ("avg_order_time", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stations",
                    models.ManyToManyField(
                        related_name="assembly_lines",
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
    ]
