# Generated by Django 4.2.7 on 2026-01-06 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "menu_management",
            "0007_allergencontrol_coursemenu_digitalthermometer_and_more",
        ),
    ]

    operations = []
