# Generated by Django 4.2.7 on 2026-01-06 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_management", "0008_auto_20260107_0133"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDefinition",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_number", models.IntegerField()),
                ("course_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("chef_notes", models.TextField(blank=True)),
                ("prep_time", models.IntegerField(default=20)),
                ("plating_time", models.IntegerField(default=5)),
                ("presentation_time", models.IntegerField(default=2)),
                ("main_ingredients", models.JSONField(default=list)),
                (
                    "complexity_level",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("medium", "Medium"),
                            ("complex", "Complex"),
                            ("chef_special", "Chef Special"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("contains_nuts", models.BooleanField(default=False)),
                ("contains_dairy", models.BooleanField(default=False)),
                ("allergens", models.JSONField(default=list)),
                ("wine_pairing_notes", models.TextField(blank=True)),
                ("beverage_pairing_notes", models.TextField(blank=True)),
                (
                    "pairing_intensity",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("bold", "Bold"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "supplement_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "course_number"],
            },
        ),
        migrations.CreateModel(
            name="CourseMenuTemplate",
            fields=[
                (
                    "template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("course_count", models.IntegerField()),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("tasting", "Tasting Menu"),
                            ("prix_fixe", "Prix Fixe"),
                            ("chef_table", "Chef Table"),
                            ("seasonal", "Seasonal"),
                            ("holiday", "Holiday"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten Free"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("price_tiers", models.JSONField(default=dict)),
                ("min_party_size", models.IntegerField(default=1)),
                ("max_party_size", models.IntegerField(default=10)),
                ("advance_booking_days", models.IntegerField(default=1)),
                ("vegetarian_available", models.BooleanField(default=True)),
                ("vegan_available", models.BooleanField(default=False)),
                ("gluten_free_available", models.BooleanField(default=False)),
                ("other_dietary_options", models.JSONField(default=list)),
                ("wine_pairing_available", models.BooleanField(default=False)),
                ("beverage_pairing_available", models.BooleanField(default=False)),
                ("sommelier_required", models.BooleanField(default=False)),
                ("is_seasonal", models.BooleanField(default=False)),
                ("season_months", models.JSONField(default=list)),
                ("holiday_specific", models.BooleanField(default=False)),
                ("holiday_name", models.CharField(blank=True, max_length=100)),
                ("chef_table_exclusive", models.BooleanField(default=False)),
                (
                    "required_chef_level",
                    models.CharField(default="line_cook", max_length=50),
                ),
                ("chef_notes", models.TextField(blank=True)),
                ("estimated_duration", models.IntegerField(default=120)),
                ("pacing_interval", models.IntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="kitchentemperaturelog",
            name="is_within_range",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WinePairing",
            fields=[
                (
                    "pairing_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wine_name", models.CharField(max_length=200)),
                (
                    "wine_type",
                    models.CharField(
                        choices=[
                            ("red", "Red Wine"),
                            ("white", "White Wine"),
                            ("sparkling", "Sparkling Wine"),
                            ("rose", "Rosé"),
                            ("dessert", "Dessert Wine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("vintage", models.IntegerField(blank=True, null=True)),
                ("pairing_notes", models.TextField()),
                (
                    "intensity_match",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("bold", "Bold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_glass",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "price_per_bottle",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "course_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wine_pairings",
                        to="menu_management.coursedefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseMenuPricing",
            fields=[
                (
                    "pricing_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier_name", models.CharField(max_length=50)),
                ("tier_description", models.TextField()),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "minimum_surcharge",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("min_party_size", models.IntegerField()),
                ("max_party_size", models.IntegerField()),
                (
                    "ingredient_quality_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "chef_level_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "seasonal_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="menu_management.coursemenutemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseMenuInstance",
            fields=[
                (
                    "instance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("table_number", models.CharField(max_length=20)),
                ("customer_count", models.IntegerField()),
                (
                    "final_price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pricing_tier_applied",
                    models.CharField(default="standard", max_length=50),
                ),
                ("dietary_requirements", models.JSONField(default=list)),
                ("special_requests", models.TextField(blank=True)),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_chef",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chef_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sommelier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sommelier_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="menu_management.coursemenutemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseInstance",
            fields=[
                (
                    "instance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_completion", models.DateTimeField()),
                ("actual_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("modifications", models.TextField(blank=True)),
                ("dietary_substitutions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.coursedefinition",
                    ),
                ),
                (
                    "kitchen_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_management.kitchenstation",
                    ),
                ),
                (
                    "menu_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_instances",
                        to="menu_management.coursemenuinstance",
                    ),
                ),
                (
                    "plating_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plating_instances",
                        to="menu_management.kitchenstation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coursedefinition",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="menu_management.coursemenutemplate",
            ),
        ),
        migrations.CreateModel(
            name="BeveragePairing",
            fields=[
                (
                    "pairing_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("beverage_name", models.CharField(max_length=200)),
                (
                    "beverage_type",
                    models.CharField(
                        choices=[
                            ("cocktail", "Cocktail"),
                            ("mocktail", "Mocktail"),
                            ("juice", "Fresh Juice"),
                            ("tea", "Specialty Tea"),
                            ("coffee", "Specialty Coffee"),
                            ("water", "Premium Water"),
                            ("soda", "Craft Soda"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pairing_notes", models.TextField()),
                (
                    "intensity_match",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("bold", "Bold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_serving",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "course_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beverage_pairings",
                        to="menu_management.coursedefinition",
                    ),
                ),
            ],
        ),
    ]
