# Generated by Django 4.2.7 on 2026-01-07 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_management", "0009_coursedefinition_coursemenutemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("prep", "Preparation"),
                            ("cooking", "Cooking"),
                            ("packaging", "Packaging"),
                            ("cleaning", "Cleaning"),
                            ("quality_control", "Quality Control"),
                        ],
                        default="prep",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=5)),
                ("current_orders", models.IntegerField(default=0)),
                ("max_orders", models.IntegerField(default=10)),
                ("equipment", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
