# Generated by Django 4.2.7 on 2026-01-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_management", "0010_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("price", "Price Test"),
                            ("description", "Description Test"),
                            ("image", "Image Test"),
                            ("position", "Position Test"),
                            ("bundle", "Bundle Test"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("control_group_size", models.IntegerField(default=50)),
                ("test_group_size", models.IntegerField(default=50)),
                (
                    "confidence_threshold",
                    models.DecimalField(decimal_places=2, default=95.0, max_digits=5),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("duration_days", models.IntegerField(default=7)),
                ("control_conversions", models.IntegerField(default=0)),
                ("test_conversions", models.IntegerField(default=0)),
                ("control_views", models.IntegerField(default=0)),
                ("test_views", models.IntegerField(default=0)),
                (
                    "significance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "confidence_interval",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("winner", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="menuoptimization",
            name="expected_impact",
        ),
        migrations.RemoveField(
            model_name="menuoptimization",
            name="implementation_status",
        ),
        migrations.RemoveField(
            model_name="menuoptimization",
            name="recommendation_type",
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="actual_cost_impact",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="actual_revenue_impact",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="ai_reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="confidence_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="data_points_analyzed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="estimated_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="expected_cost_reduction",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="expected_order_increase",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="expected_revenue_increase",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="implementation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="implementation_steps",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="optimization_type",
            field=models.CharField(
                choices=[
                    ("pricing", "Pricing Optimization"),
                    ("placement", "Menu Placement"),
                    ("bundle", "Bundle Suggestion"),
                    ("promotion", "Promotion Strategy"),
                    ("inventory", "Inventory Optimization"),
                ],
                default="pricing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="required_resources",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("implemented", "Implemented"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuoptimization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="menuoptimization",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_management.virtualbrand",
            ),
        ),
        migrations.AlterField(
            model_name="menuoptimization",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="menuoptimization",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low Priority"),
                    ("medium", "Medium Priority"),
                    ("high", "High Priority"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("overview", "Overview Dashboard"),
                            ("sales", "Sales Analytics"),
                            ("menu", "Menu Performance"),
                            ("customer", "Customer Behavior"),
                            ("operational", "Operational Metrics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ABTestVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("position", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.recipemenuitem",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menu_management.abtest",
                    ),
                ),
            ],
        ),
    ]
