# Generated by Django 4.2.7 on 2026-01-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_assigned_to_order_estimated_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "menu_management",
            "0012_costanalysis_wastetracking_stationassignment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeMenuItemLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary_recipe", models.BooleanField(default=True)),
                ("auto_created", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_links",
                        to="orders.menuitem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_links",
                        to="menu_management.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe-Menu Item Link",
                "unique_together": {("recipe", "menu_item")},
            },
        ),
    ]
