# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0015_fix_foreign_key_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedOrderQueue',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('pos', 'POS System'), ('delivery', 'Delivery Platform'), ('online', 'Online Ordering'), ('phone', 'Phone Order'), ('walkin', 'Walk-in')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('new', 'New Customer'), ('repeat', 'Repeat Customer')], default='regular', max_length=20)),
                ('items', models.JSONField(default=list)),
                ('special_requests', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('promised_time', models.DateTimeField(blank=True, null=True)),
                ('prep_time_estimate', models.IntegerField(default=15)),
                ('actual_prep_time', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('batched', 'Batched'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('batch_position', models.IntegerField(default=0)),
                ('assigned_station', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_orders', to='menu_management.virtualbrand')),
                ('assigned_chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='auth.user')),
                ('kitchen_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu_management.kitchenorder')),
            ],
        ),
    ]
