# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0016_recreate_unified_order_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedorderqueue',
            name='pos_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu_management.posorder'),
        ),
        migrations.AddField(
            model_name='unifiedorderqueue',
            name='delivery_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu_management.deliveryorder'),
        ),
    ]
