# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0017_add_missing_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlatform',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, editable=False)),
                ('platform', models.CharField(choices=[('uber_eats', 'Uber Eats'), ('doordash', 'DoorDash'), ('grubhub', 'Grubhub'), ('postmates', 'Postmates'), ('deliveroo', 'Deliveroo'), ('just_eat', 'Just Eat'), ('swiggy', 'Swiggy'), ('zomato', 'Zomato'), ('foodpanda', 'Foodpanda'), ('seamless', 'Seamless')], max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500)),
                ('store_id', models.CharField(blank=True, max_length=100)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, default=0.15, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('syncing', 'Syncing'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_platforms', to='menu_management.virtualbrand')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, editable=False)),
                ('platform_order_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_time', models.IntegerField(help_text='Minutes')),
                ('status', models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateTimeField(null=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='menu_management.deliveryplatform')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPerformance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, editable=False)),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('average_time', models.IntegerField(help_text='Minutes', null=True, blank=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='menu_management.deliveryplatform')),
            ],
        ),
    ]
