# Generated by Django 4.2.7 on 2026-01-06 21:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_party_size", models.PositiveIntegerField(default=20)),
                ("min_reservation_time", models.TimeField(default="17:00")),
                ("max_reservation_time", models.TimeField(default="23:00")),
                ("reservation_advance_days", models.PositiveIntegerField(default=90)),
                ("auto_confirmation", models.BooleanField(default=True)),
                ("deposit_required_venue", models.BooleanField(default=True)),
                (
                    "deposit_percentage",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
                ),
                (
                    "cancellation_policy",
                    models.TextField(
                        default="Cancellations must be made at least 24 hours in advance for a full refund."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservation Settings",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.CharField(max_length=10, unique=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("booth", "Booth"),
                            ("private", "Private"),
                            ("outdoor", "Outdoor"),
                            ("bar", "Bar"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("main_dining", "Main Dining Room"),
                            ("private_room", "Private Room"),
                            ("outdoor_patio", "Outdoor Patio"),
                            ("bar_area", "Bar Area"),
                            ("lounge", "Lounge"),
                        ],
                        default="main_dining",
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("min_party_size", models.PositiveIntegerField(default=1)),
                ("max_party_size", models.PositiveIntegerField(default=8)),
            ],
            options={
                "ordering": ["table_number"],
            },
        ),
        migrations.CreateModel(
            name="VenueReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding Reception"),
                            ("corporate", "Corporate Event"),
                            ("birthday", "Birthday Party"),
                            ("anniversary", "Anniversary"),
                            ("fundraiser", "Fundraiser"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("private_party", "Private Party"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "expected_guests",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                (
                    "catering_options",
                    models.TextField(help_text="Describe catering requirements"),
                ),
                (
                    "setup_requirements",
                    models.TextField(
                        blank=True, help_text="Special setup requirements"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_1000", "Under $1,000"),
                            ("1000_5000", "$1,000 - $5,000"),
                            ("5000_10000", "$5,000 - $10,000"),
                            ("10000_25000", "$10,000 - $25,000"),
                            ("over_25000", "Over $25,000"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("deposit_paid", "Deposit Paid"),
                            ("fully_paid", "Fully Paid"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="inquiry",
                        max_length=20,
                    ),
                ),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmation_code", models.CharField(max_length=10, unique=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TableReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "party_size",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual Dining"),
                            ("business", "Business Meeting"),
                            ("celebration", "Celebration"),
                            ("date_night", "Date Night"),
                            ("family", "Family Gathering"),
                            ("romantic", "Romantic Dinner"),
                            ("special_occasion", "Special Occasion"),
                        ],
                        max_length=50,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("seated", "Seated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmation_code", models.CharField(max_length=8, unique=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.table"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
    ]
