# Generated by Django 4.2.7 on 2026-01-06 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_dailymealoption_mealpassselection"),
    ]

    operations = []
