# Generated by Django 4.2.7 on 2026-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_assigned_to_order_estimated_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit/Debit Card"),
                    ("online", "Online Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
