# Generated by Django 4.2.7 on 2026-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealpasssubscription",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit/Debit Card"),
                    ("online", "Online Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
